sampler:
  mcmc:
    learn_proposal: True
    burn_in: 10
    oversample_power: 1
    drag: True
    measure_speeds: True
    max_samples: 100000

params:
  logA:
    prior:
      min: 1.61
      max: 3.91
    ref:
      dist: norm
      loc: 3.05
      scale: 0.001
    proposal: 0.001
    latex: \log(10^{10} A_\mathrm{s})
    drop: true

  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}

  ns:
    prior:
      min: 0.8
      max: 1.2
    ref:
      dist: norm
      loc: 0.965
      scale: 0.004
    proposal: 0.002
    latex: n_\mathrm{s}

  H0:
    prior:
      min: 60
      max: 80
    ref:
      dist: norm
      loc: 70.
      scale: 0.0001
    proposal: 0.0001
    latex: H_0

  mnu:
    prior:
      min: 0.05
      max: 0.08
    ref:
      dist: norm
      loc: 0.06
      scale: 0.0001
    proposal: 0.0001
    latex: m_\nu
    
  ombh2:
    prior:
      min: 0.005
      max: 0.1
    ref:
      dist: norm
      loc: 0.0224
      scale: 0.0001
    proposal: 0.0001
    latex: \Omega_\mathrm{b} h^2

  omch2:
    prior:
      min: 0.001
      max: 0.99
    ref:
      dist: norm
      loc: 0.12
      scale: 0.001
    proposal: 0.0005
    latex: \Omega_\mathrm{c} h^2

  tau:
    prior:
      min: 0.01
      max: 0.8
    ref:
      dist: norm
      loc: 0.055
      scale: 0.006
    proposal: 0.003
    latex: \tau_\mathrm{reio}

#  sigma8:
#    latex: \sigma_8
#  s8h5:
#    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
#    latex: \sigma_8/h^{0.5}

#  A:
#    derived: 'lambda A_s: 1e9*A_s'
#    latex: 10^9 A_\mathrm{s}
#  clamp:
#    derived: 'lambda A_s, tau_reio: 1e9*A_s*np.exp(-2*tau_reio)'
#    latex: 10^9 A_\mathrm{s} e^{-2\tau}
#  age:
#    latex: '{\rm{Age}}/\mathrm{Gyr}'


  galshcl_DESgc0_b0:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.41
      scale: 0.1
    proposal: 0.13
    
  galshcl_DESgc1_b0:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.12
    
  galshcl_DESgc2_b0:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.11
    
  galshcl_DESgc3_b0:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.91
      scale: 0.1
    proposal: 0.14
    
  galshcl_DESgc4_b0:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.96
      scale: 0.1
    proposal: 0.14
    
  galshcl_DESgc0_b1:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.41
      scale: 0.1
    proposal: 0.13
    
  galshcl_DESgc1_b1:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.12
    
  galshcl_DESgc2_b1:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.11
    
  galshcl_DESgc3_b1:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.91
      scale: 0.1
    proposal: 0.14
    
  galshcl_DESgc4_b1:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.96
      scale: 0.1
    proposal: 0.14
    
  galshcl_DESgc0_b2:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.41
      scale: 0.1
    proposal: 0.13
    
  galshcl_DESgc1_b2:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.12
    
  galshcl_DESgc2_b2:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.11
    
  galshcl_DESgc3_b2:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.91
      scale: 0.1
    proposal: 0.14
    
  galshcl_DESgc4_b2:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.96
      scale: 0.1
    proposal: 0.14
    
  galshcl_DESgc0_bs:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.41
      scale: 0.1
    proposal: 0.13
    
  galshcl_DESgc1_bs:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.12
    
  galshcl_DESgc2_bs:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.11
    
  galshcl_DESgc3_bs:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.91
      scale: 0.1
    proposal: 0.14
    
  galshcl_DESgc4_bs:
    prior:
      min: -3.000
      max: 3.000
    ref:
      dist: norm
      loc: 1.96
      scale: 0.1
    proposal: 0.14

  galshcl_DESwl0_m:
    prior:
      dist: norm
      loc: 0.012
      scale: 0.023
    ref:
      dist: norm
      loc: 0.012
      scale: 0.01
    proposal: 0.005
    
  galshcl_DESwl1_m:
    prior:
      dist: norm
      loc: 0.012
      scale: 0.023
    ref:
      dist: norm
      loc: 0.012
      scale: 0.01
    proposal: 0.005
    
  galshcl_DESwl2_m:
    prior:
      dist: norm
      loc: 0.012
      scale: 0.023
    ref:
      dist: norm
      loc: 0.012
      scale: 0.01
    proposal: 0.005
    
  galshcl_DESwl3_m:
    prior:
      dist: norm
      loc: 0.012
      scale: 0.023
    ref:
      dist: norm
      loc: 0.012
      scale: 0.01
    proposal: 0.02
    
  galshcl_DESgc0_dz:
    prior:
      dist: norm
      loc: 0.000
      scale: 0.007
    ref:
      dist: norm
      loc: 0.000
      scale: 0.007
    proposal: 0.005
    
  galshcl_DESgc1_dz:
    prior:
      dist: norm
      loc: 0.000
      scale: 0.007
    ref:
      dist: norm
      loc: 0.000
      scale: 0.007
    proposal: 0.005
    
  galshcl_DESgc2_dz:
    prior:
      dist: norm
      loc: 0.000
      scale: 0.006
    ref:
      dist: norm
      loc: 0.000
      scale: 0.006
    proposal: 0.005
    
  galshcl_DESgc3_dz:
    prior:
      dist: norm
      loc: 0.000
      scale: 0.01
    ref:
      dist: norm
      loc: 0.000
      scale: 0.01
    proposal: 0.005
    
  galshcl_DESgc4_dz:
    prior:
      dist: norm
      loc: 0.000
      scale: 0.01
    ref:
      dist: norm
      loc: 0.000
      scale: 0.01
    proposal: 0.005
    
  galshcl_DESwl0_dz:
    prior:
      dist: norm
      loc: -0.001
      scale: 0.016
    ref:
      dist: norm
      loc: -0.001
      scale: 0.016
    proposal: 0.005
    
  galshcl_DESwl1_dz:
    prior:
      dist: norm
      loc: -0.019
      scale: 0.013
    ref:
      dist: norm
      loc: -0.019
      scale: 0.013
    proposal: 0.005
    
  galshcl_DESwl2_dz:
    prior:
      dist: norm
      loc: 0.009
      scale: 0.011
    ref:
      dist: norm
      loc: 0.009
      scale: 0.011
    proposal: 0.005
    
  galshcl_DESwl3_dz:
    prior:
      dist: norm
      loc: -0.018
      scale: 0.022
    ref:
      dist: norm
      loc: -0.018
      scale: 0.022
    proposal: 0.005
    
  galshcl_A_IA:
    prior:
      min: -5.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.
      scale: 0.2
    latex: A_{\rm IA}
    proposal: 0.1
    
  galshcl_eta_IA:
    prior:
      min: -5.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.
      scale: 0.2
    latex: \eta_{\rm IA}
    proposal: 0.1

# CCL settings
theory:
#  classy:
#    extra_args:
#      non linear: hmcode
#      hmcode_min_k_max: 20
#      N_ncdm: 1
#      N_ur: 2.0328
  camb:
     extra_args:
#       num_massive_neutrinos: 0
  galshcl_like.CLCCL:
    transfer_function: boltzmann_camb
    matter_pk: halofit
    baryons_pk: nobaryons
    kmax: 20.
#    output_params:
#      - sigma8


# Likelihood settings
likelihood:
  galshcl_like.GalshClLike:
    # Input sacc file
    input_file: /users/boryanah/repos/hybrid_eft_nbody/data/cls_covG_covNG_DESgc_DESwl.fits
    # List all relevant bins
    bins:
      - name: DESgc0
      - name: DESgc1
      - name: DESgc2
      - name: DESgc3
      - name: DESgc4
      - name: DESwl0
      - name: DESwl1
      - name: DESwl2
      - name: DESwl3
    # List all 2-points that should go into the
    # data vector
    twopoints:
      - bins: [DESgc0, DESgc0]
      - bins: [DESgc1, DESgc1]
      - bins: [DESgc2, DESgc2]
      - bins: [DESgc3, DESgc3]
      - bins: [DESgc4, DESgc4]
      
      - bins: [DESgc0, DESwl0]
      - bins: [DESgc0, DESwl1]
      - bins: [DESgc0, DESwl2]
      - bins: [DESgc0, DESwl3]
      - bins: [DESgc1, DESwl0]
      - bins: [DESgc1, DESwl1]
      - bins: [DESgc1, DESwl2]
      - bins: [DESgc1, DESwl3]
      - bins: [DESgc2, DESwl0]
      - bins: [DESgc2, DESwl1]
      - bins: [DESgc2, DESwl2]
      - bins: [DESgc2, DESwl3]
      - bins: [DESgc3, DESwl0]
      - bins: [DESgc3, DESwl1]
      - bins: [DESgc3, DESwl2]
      - bins: [DESgc3, DESwl3]
      - bins: [DESgc4, DESwl0]
      - bins: [DESgc4, DESwl1]
      - bins: [DESgc4, DESwl2]
      - bins: [DESgc4, DESwl3]
      
      - bins: [DESwl0, DESwl0]
      - bins: [DESwl0, DESwl1]
      - bins: [DESwl0, DESwl2]
      - bins: [DESwl0, DESwl3]
      - bins: [DESwl1, DESwl1]
      - bins: [DESwl1, DESwl2]
      - bins: [DESwl1, DESwl3]
      - bins: [DESwl2, DESwl2]
      - bins: [DESwl2, DESwl3]
      - bins: [DESwl3, DESwl3]
    # Default scale cuts
    defaults:
      DESgc0:
        lmax: 145
        lmin: 0
      DESgc1:
        lmax: 225
        lmin: 0
      DESgc2:
        lmax: 298
        lmin: 0
      DESgc3:
        lmax: 371
        lmin: 0
      DESgc4:
        lmax: 435
        lmin: 0
      DESwl0:
        lmax: 2000
        lmin: 30
      DESwl1:
        lmax: 2000
        lmin: 30
      DESwl2:
        lmax: 2000
        lmin: 30
      DESwl3:
        lmax: 2000
        lmin: 30
    # Prefix associated to all nuisance params
    input_params_prefix: galshcl
    # IADESY1, IAPerBin or IANone
    ia_model: IADESY1
    # NzShift or NzNone
    nz_model: NzShift
    # PkDefault, PkHModel
    pk_model: PkDefault
    # Linear or HEFT
    bz_model: Linear

debug: False

output: 'cobaya_out/des_heft'
